---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

<<<<<<< HEAD
before_install:
  - npm config set spin false
=======
branches:
  only:
    - master
>>>>>>> 2036585... message

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
