version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kkl
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
