name: End to End Testing on Push

on: push

jobs:
  buildAndTestOnPush:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - uses: actions/checkout@v2

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

       # Yarn cache dir
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn  --frozen-lockfile

      # Install project dependencies, test and build
      - name: Install dependencies
        run:  yarn --cwd ./frontend  --frozen-lockfile
      - name: Run build
        run:  yarn --cwd ./frontend build --prod

      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn --cwd ./server --frozen-lockfile
  cypress-run:
    name: E2E on Chrome
    runs-on: ubuntu-16.04
    needs: buildAndTestOnPush
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install YARN dependencies, cache them correctly
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn  --frozen-lockfile

      # Install project dependencies, test and build
      - name: Install dependencies
        run:  yarn --cwd ./frontend  --frozen-lockfile
      - name: Run build
        run:  yarn --cwd ./frontend build --prod

      # Install project dependencies, test and build
      - name: Install dependencies
        run: yarn --cwd ./server --frozen-lockfile

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn --cwd ./server start, yarn --cwd ./frontend start:local
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3000
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots